# Generated by Django 5.1.1 on 2024-09-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_perfil_biografia_alter_perfil_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_de_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
