# Generated by Django 5.1.1 on 2024-09-25 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_fecha_de_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_de_registro',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
