# Generated by Django 5.1.1 on 2024-09-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_fecha_de_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='matricula',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='profesional',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
