# Generated by Django 5.1.1 on 2024-09-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_alter_usuario_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='matricula',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profesional',
            field=models.BooleanField(),
        ),
    ]
