# Generated by Django 5.1.1 on 2024-09-23 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=30)),
                ('texto', models.TextField()),
                ('apellido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
