# Generated by Django 5.1.1 on 2024-09-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='apellido',
            new_name='autor',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='usuario',
        ),
    ]
